name: Pipelines Successful
on:
  workflow_call

jobs:
  pipelines_job:
    runs-on: ubuntu-latest
    steps:
      - name: Pre-target failing
        run: exit 1
      - name: "[TerragruntExecute]: Test"
        run: echo "Success"
      - name: Post-target step
        run: echo "Success"
